### ISSUE TITLE
 В lldControlSetRawMotorPower исправить диапазоны скважности

### ISSUE THREAD

**Issue by serykhelena** [MikhaylovNikita/Diploma_BB_8#5]
Скважность изменяется от 0 до `pwmWidth`, поэтому в функции может понадобиться ещё аргумент по заданию направления вращения двигателя. 
В функции с заданием %-в, уже можно смотреть на знак, типа -100% - полный назад, 100% - полный вперёд.

**Comment by MikhaylovNikita** [comment]
f2c58b7 fixed
